### ISSUE TITLE
help menu

### ISSUE THREAD

**Issue by darknessneo** [Odie/skyui-vr#13]
Dont know if this is directly from skyUI but i noticed that the help menu is a little bugy. Somes options dont display the text

**Comment by Odie** [comment]
Okay, will look into this. =)

**Comment by Odie** [comment]
Okay... here's what happened:

1. Some bugs were introduced with help text retrieval
This was never properly tested. Basically, any help text that contained VR platform specific help text were not being correctly retrieved. This has all been fixed and tested.

2. Missing VR icons
The help text uses a whole separate set of icons than the rest of the interface. So even though the button prompts are showing new VR icons correctly, the help text did not have access to them. A set of high res icons were reimported from vanilla UI's swf file.

Anyway, the help text should be fixed as of bc68ee5ce749149b2a0f565f572299f9fd56eee3. The fix will be rolled out at the end of the week other fixes, if any. =)

Thanks for letting me know something was broken! It's now better!
