### ISSUE TITLE
add category memory for craft menu

### ISSUE THREAD

**Issue by darknessneo** [Odie/skyui-vr#17]
it is possible to add the same future as inventory "category memory" for craftmenu?
I have alot of armors, and since we have all type in only one category, im going crazy when i accidentaly switch!

**Comment by Odie** [comment]
alrighty. Will look into this. =)

**Comment by Odie** [comment]
This has been implemented by 62cdd193c0ed86812225dd75113f9d674f22288e and is available as a part of release [v1.0-beta.3](https://github.com/Odie/skyui-vr/tree/v1.0-beta.3).

There was very little testing done on this. But it appears to function without issue.
