### ISSUE TITLE
Wonderful!

### ISSUE THREAD

**Issue by Grestorn** [Odie/skyui-vr#20]
Hi Odie,
Since there's no other way to contact you, I had to use this. 

Just wanted to say that it's wonderful that you started to adapt SkyUI. I've been waiting for this so long! It's working really good already, perfectly usable for me. 

Coincidently I saw that you also commented on a pull request I made for DragonbornSpeaksNaturally, which unfortunately never got picked up...

It's been quite a while since I've done any papyrus scripting and I'm not sure if I ever want to go back to that, but never say never - maybe there'll be some contribution from my side to sometime.

**Comment by Odie** [comment]
Hi Grestorn!

Good to hear from you. Let me know if you have any suggestions on how to improve things.

Btw, you can find me on reddit as u/Superodie or Odie#2665 on Discord.
