### ISSUE TITLE
Here is a ss what i see when looking at armour and were i miss the info

### ISSUE THREAD

**Issue by Skidrow68** [Odie/skyui-vr#24]
Attach a ss with a ring were the info should be if its better or not then the one i have on me, this one should have been +6.
![missing info](https://user-images.githubusercontent.com/19759240/48317653-7e173b00-e5f5-11e8-969c-363c11047f77.jpg)

**Comment by Skidrow68** [comment]
> Attach a ss with a ring were the info should be if its better or not then the one i have on me, this one should have been +6.
> ![missing info](https://user-images.githubusercontent.com/19759240/48317653-7e173b00-e5f5-11e8-969c-363c11047f77.jpg)

**Comment by Odie** [comment]
Hmm! Looks like the armor rating is still missing?

Are you using the rebuilt version? https://github.com/Odie/skyui-vr/releases/download/v1.0-beta.3/SkyUI.-.VR.v1.0-beta.3.rebuilt.7z

**Comment by Skidrow68** [comment]
Yes.

**Comment by Skidrow68** [comment]
One other thing i realy would like is deadszon left and rigth when your in menus like items, spells and so, as it is now you scroll down to get to gloves and it moves to other menu….

**Comment by Odie** [comment]
Hopefully, it's fixed this time. Let me know how this build works for you. =)

[SkyUI - VR - armor rating fix.zip](https://github.com/Odie/skyui-vr/files/2574825/SkyUI.-.VR.-.armor.rating.fix.zip)

**Comment by Skidrow68** [comment]
Yes now it works, thank you :)

Is it posible to add dead-zon left and rigth on the touchpad when your in menus like items?

**Comment by baggyg** [comment]
Confirmed here as well. The latest fix worked for me.

**Comment by Odie** [comment]
Great! A new version has been published. =)

**Comment by Odie** [comment]
@Skidrow68 Adding a dead-zone isn't possible at the moment, since SkyUI does not perform low level input handling (yet). All SkyUI is getting is up/down/right/left signals after the low level stuff has been handled by the game.

This might improve or become possible with #9, which enables SkyUI to, for example, watch the touchpad directly and decide what to do on its own, instead of relying on the game. But this might take some time to materialize.

**Comment by Odie** [comment]
Thanks everybody for reporting this bug! Really need everybody's continual input to make this thing better! =)

**Comment by Skidrow68** [comment]
Ok when it was locked i tought it was locked :)
