### ISSUE TITLE
Beta4 - WMR Motion Controller Buttons Not Bound

### ISSUE THREAD

**Issue by angrmgmt** [Odie/skyui-vr#28]
Using Beta4, on Lenovo Explorer.  Buttons are all properly auto-mapped in game, work for everything (motion, system menu, journal, map, etc.) up until I try to loot the first chest.  The interface has only minimal functionality:

- No change between containers by pressing left from "All"; instead selects right-most tab
- No ability to take/take all
- Buttons labeled incorrectly for controller
- Only able to move selection around (including between tabs) and use the grip buttons to back out

If I remember correctly the buttons shown are A, RT/LT, B, Space, X.  Will edit if not (see edit below), but it was definitely some mix of keyboard/controller.  I was expecting like "Grip", "LT/RT", the little touchpad button thing, etc.  Either way pressing almost every button on the controller does nothing.  Two open Steam menus and two leave.  That's it.

Using SKSEVR 2.0.10 for runtime 1.4.15, with scripts installed in MO2.  I've also tried just putting the Scripts folder directly into the game's Data folder, no dice.

Side note:  feeling awesome starting up again, installing over 200 mods and everything works except a fantastic, surprising beta!!  Wasn't expecting to see this.  Will be nice to get this little speed bump out of the way.

EDIT:  I've confirmed that depending on context (so that is somewhat working), I'll have anything between "A", "X", "Y", "Space", "Shift", "LT/RT", "LS" with a little up indicator on it, and so on.  It's mixing and matching control styles/keys somehow.  I was able to use "X" (which I found out was my touchpad's up button) to drop an item from my inventory (and pick it right back up, no problem in the main game).  Still nothing works in the chest interface, and I wasn't able to sort my inventory with double up taps on my thumbstick.

**Comment by angrmgmt** [comment]
Happy to help in any way I can.  This is a noble endeavor!

If we can at least get it so that I can take/equip/take all from the first chest in the game, that would be a good start!  I can figure out whatever button mapping it turns out to be (like I did with drop in the inventory), but it just seems like almost nothing is bound to my particular controller, specifically in the looting interface.  I'll collect a more thorough report of the functionality/display and reply below.

I feel like I'm competent enough to have installed it correctly, having set up and played through 6 modded Bethesda games over 10+ years, but I could have done something dumb there, too.  Is there a config file I missed?  'config.txt' looks like it's just the backing file for the MCM menu.

Is it the order of operations when starting up?  WMR is weird because it has this "Cliff House" thing MS did, and I've found the best results in Elite:Dangerous when I start E:D directly and let it start up the Cliff House and SteamVR; otherwise my performance tanks.  In the case of Skyrim VR, if I start CH and SteamVR first (to try to ensure that my setup and controllers are recognized, you never know) SKSE fails to load, and none of the SKSE-based mods can start, nor obviously anything from DLL Loader, as though it's launching Skyrim VR directly, despite using an MO2 shortcut to the sksevr_loader.

We can worry about sorting and container swapping when I have some items.  :)

**Comment by Odie** [comment]
Wow, can’t even take items from a container?

Even though the button prompts aren’t being displayed correctly, the button presses *should* be properly handled still. You ought to be able to take an item by pressing the trackpad center. The triggers on either hand ought to equip the item/spell into that hand.

—

Not entirely sure what you mean by skse not loading. Are you saying when you launch the game via the skse shortcut in MO, skse doesn’t seem to actually load? Is there a skse.log?

**Comment by angrmgmt** [comment]
As mentioned, WMR has a weird tie-in to Microsoft's Mixed Reality Portal, colloquially referred to as the "Cliff House".  It is a piece of bloatware, in my opinion, but regardless, you have to have it; uninstalling means no VR in applications.  **If and only if I run it first**, prior to launching the game, I get no SKSE functionality, despite using a shortcut on my taskbar for sksevr_loader created in MO2 (the Target is '...\MO2\ModOrganizer.exe "moshortcut://:SKSEVR" ').

If I start Skyrim VR via this shortcut without Cliff House and Steam VR running first, it will correctly launch the CH, then SteamVR, then load SKSE.  It's easy to tell with my load order when SKSE is running properly, without even checking getskseversion from the console - there are quite a few mods requiring it that have startup messages, and those become errors (usually with modal pop ups) if it's not running.

**Comment by angrmgmt** [comment]
Okay, when I just tried to collect info I got only partway through, as the Inventory stopped working, and I got stuck zoomed into the footwraps... no amount of button pressing, joystick wiggling, touching, tapping, pressing, etc. would get me out of there, though I could access the Skyrim System Menu by first going to the WMR Menu using the Windows button on either stick, then backing up one step.  So that's new.

Before that problem, I was able to collect info on the Chest interface:

With a category (All, Armor, etc.) selected, the buttons/keys shown were:
B - Exit
Space - Search
LB RB - Column
LS (up) - Order
Back - Switch Tab
X - Take All

With an item selected (Gold in this case), the buttons/keys shown were:
A - Take
RT LT - Use
X - Take All

With armor selected (a helmet in this case), the buttons/keys shown were:
A - Take
RT LT - Equip
X - Take All

In any of the three situations, the only buttons that worked were:
Windows Button - Brings up WMR floating menu
Press Stick In - Brings up SteamVR Dashboard
Grip (L or R) - Cancel/Exit

Keyboard input is also not accepted, so I couldn't use Space or the 'B' key for example to test that.

**Comment by angrmgmt** [comment]
Figured out what the problem is:  Chesko's mods (Campfire/Frostfall) provide .swf files overwriting those provided by SkyUI, which worked for SkyUI SE, but no longer match SkyUI VR.  When I disable them everything works perfectly.  Wonderful job on this!

Any experience with editing .swf's?  All of his stuff is [up on GitHub](https://github.com/chesko256/Campfire)...  :)

Also I found one minor typo going through the code while I was bored:

In /src/Common/skyui/defines/ButtonArtNames.as, Line 169:

`"MR MENU_LEFT", "MR MENU_HOLD", "ME MENU", ...`

Should probably be "MR MENU", right?  Cheers.

**Comment by Odie** [comment]
Haha... okay. I guess that’s to be expected.

I looked into campfire and frostfall compatibility some time ago. Campfire on its own worked fine, but frostfall did not. Besides having SkyUI files that were not compatible with VR, the mod also relied on papyrus util, which only became available for VR maybe in the past two weeks,

Anyway, I can look into adding frostfall compatibility again.

You might ant to follow this issue: 
https://github.com/Odie/skyui-vr/issues/15

**Comment by Odie** [comment]
Yeah, “ME menu” is probably a typo. Thanks for catching that! =)

**Comment by angrmgmt** [comment]
You bet.  Thank YOU for your work.
