### ISSUE TITLE
Add scrolling to the Stats Page

### ISSUE THREAD

**Issue by Odie** [Odie/skyui-vr#29]
The Stats page does not seem to scroll to reveal more content as reported here:
https://www.reddit.com/r/skyrimvr/comments/9hrj3z/skyui_vr/ed7by62

**Comment by Odie** [comment]
As it turns out, the stat page never had the ability to scroll using controllers. At least the code that might handle such a behavior is entirely missing. It might have worked with the mouse on PC, since the scroll list seems to handle mouse wheel events on its own.

**Comment by Odie** [comment]
[SkyUI - VR - stats page scroll.zip](https://github.com/Odie/skyui-vr/files/2729221/SkyUI.-.VR.-.stats.page.scroll.zip)

A fix is provided here for testing purposes.

**Comment by leovogel** [comment]
@Odie Your fix worked for me. Thanks for you effort! I hope this gets merged into the next official release.

**Comment by Odie** [comment]
Oh wow. I forgot all about this. Should have released this one looong ago. X)

**Comment by Odie** [comment]
Merged with 2192dc8
