### ISSUE TITLE
Show Active Effect in HUD

### ISSUE THREAD

**Issue by themerson** [Odie/skyui-vr#33]
HUD doesn't show active effects, even if enabled in MCM

**Comment by Odie** [comment]
I’m not sure if it would be possible at all to add additional widgets to the screen. 

Admittedly, I haven’t looked into this much.  But having a menu shown in the game world requires additional polygon to be prepared and submitted to the GPU, along with the menu having properly rendered to some texture, of course.

As an example, take a look at the compass. It’s very different from flatrim. A small widget is mapped onto a rounded surface and floated right around your character.

Showing active effects will probably be easier with something like MageVR where it is already rendering/overlaying something on top of the game world.
