### ISSUE TITLE
Uninstall mod prevents saving

### ISSUE THREAD

**Issue by Turgrodan** [Odie/skyui-vr#37]
On my system, when I uninstall this mod, I can no longer save my game without the game crashing.  So I have to use this mod whether I want to or not.  Either that or start the game from scratch which I'm not going to do.

**Comment by Odie** [comment]
Hi there,

Skyui comes with a bunch of swf file that overrides the default game menus. These can be removed/replaced without issue.

The other part of skyui is infrastructure for other mods to present their settings, aka mcm. If something is causing a crash, this is most likely the reason. Though I don’t know why this might only happen during file save.

Also, if you uninstall skyui, you’ll want to uninstall other mods that depend on the mcm also.

Lastly, it is not usually advisable to uninstall major mods half way through a play through. This is just the consequence of how the game engine works. When mods are installed, it might leave around traces of running scripts or other data that might have trouble finding files/data that it expects would be available, but is not. There really isn’t much that can be done about this.
