### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by lnsaneshane** [Odie/skyui-vr#41]
i down load the link. i load up mod organizer 2. go to the tab to manually download it. click the folder. but there is only several more folders in the first but no SkyUI_SE.esp. there is when i click on the folder from my downloads folder but not when i go through mod organizer 2. what am i doing wrong?

**Comment by Odie** [comment]
I don’t entirely understand what you are describing.

Here are the two steps to install the mod:
1. Download the .7z file (https://github.com/Odie/skyui-vr/releases/download/v1.0-beta.4/SkyUI-VR.v1.0-beta.4.7z)

2. Drop the 7z file over the MO2 UI
You don’t need to unpack the file.

Hope this helps.

**Comment by lnsaneshane** [comment]
i figured it out. when i downloaded it, it was not in a 7zip or something so i had to compress it. im sure im not making sense but it should be good now thanks for the timely response

**Comment by Dwarfkicker** [comment]
When you open the downloaded file. There is no file called skyUI.vr1.......... an so on.
I use MO2 for modding . Were Can i get this file![image](https://user-images.githubusercontent.com/67874564/86540182-87a89180-bf03-11ea-82c2-b1097c927291.png)

**Comment by Dwarfkicker** [comment]
I get this on my pc when i download the skyUI from github? The one from youtube guide is different from mine . ![image](https://user-images.githubusercontent.com/67874564/86540215-d6562b80-bf03-11ea-85d3-4041dbdfda10.jpeg)
Or do i just drag and drop the ![image](https://user-images.githubusercontent.com/67874564/86540255-08678d80-bf04-11ea-99f9-34efb62c1dd8.jpeg)in to MO2?

**Comment by Odie** [comment]
@Dwarfkicker Just drag and drop it over the mo2 window.

**Comment by Odie** [comment]
Closing old issue
