### ISSUE TITLE
mods not showing in mcm

### ISSUE THREAD

**Issue by mr2meowsYT** [Odie/skyui-vr#46]
cant use magevr bruh this is shit

**Comment by Odie** [comment]
You may want to check if skse is installed correctly. There are various script files that also need to be installed. 

If you’re still having trouble, please do ask for help on r/skyrimvr. The community is usually quite happy to help newcomers.

**Comment by mr2meowsYT** [comment]
k im gonna uninstall the skse vr version and install the flat version

**Comment by Odie** [comment]
Alrighty. Good luck!
