### ISSUE TITLE
seems to not detect SKSEVR even though i have it installed

### ISSUE THREAD

**Issue by judess69er** [Odie/skyui-vr#47]
im using the latest version's of both mods, My SKSEVR is installed correctly because i have mods that depend on it and work fine with it.

**Comment by Odie** [comment]
I’ve been away from the game for a long time. IIRC, it’s easy to miss installing the pex files packed with skse which would cause Skyui to not function correctly.

If that’s not the issue, you may want to seek help on r/skyrimvr. Besides keeping various modding guides to help new comers, they are usually happy to provide some assistance to help you get going.

**Comment by matios13** [comment]
@judess69er  @Odie I have the same problem.
Did you manage to make it work?

**Comment by Odie** [comment]
Closing old issue
