### ISSUE TITLE
skyrim vr update has broken skyui

### ISSUE THREAD

**Issue by KlausKlavier** [Odie/skyui-vr#49]
several of my mods no longer function and will not load in without skyui updated, there must have been a random game update and now several mods do not work. it gives me a message that it is skyui

**Comment by Odie** [comment]
Hi there,

I’m not aware of any new versions of skyrimvr. A quick google seems to show that the last new version was released in 2018.

It more likely that something about your load order changed. Maybe you added a mod recently that came packaged with some version of skyui that’s meant for SE?

**Comment by KlausKlavier** [comment]
I think I found the issue SKSEVR wasn’t launching properly everything seems to be working now. Sorry for the false alarm

**Comment by Odie** [comment]
Glad you found the problem. :)
