### ISSUE TITLE
Thanks for This and for still dealing with Users.

### ISSUE THREAD

**Issue by rbturcott** [Odie/skyui-vr#50]
Just wanted to thank you for this program and for dealing politely with the often silly problems people are having with it.
It's worked great for me and I've got well over a hundred mods running.  Some of the big ones.  And running Skyrim in VR with mods is the best, and this program is a critical part of that. :-)

**Comment by Odie** [comment]
Thank you for the kind words!

Honestly, the primary reason for porting skyui was so I can penjoy the game. X) There are just so many mods that needs it. I’m glad it was helpful to everyone else as well though!

Anyway, hope you’re enjoying the game. I need to find the time to get back into it also.
