### ISSUE TITLE
Arrows are erroneously categorised as type:bolt

### ISSUE THREAD

**Issue by VirtualRageMaster** [Odie/skyui-vr#52]
It seems that all arrows have been given the category type:bolt

Checked with other users and they have confirmed when loading unmodded Skyrim VR with ONLY SkyUI VR

This breaks other mods that rely upon detecting arrows in inventory. For instance, Simple Realistic Archery VR omits type:bolt items when populating dropdown selection lists for selecting arrows, and therefore these lists as a result appear empty even though arrows are present in the player inventory.

**Comment by Odie** [comment]
Fixed with 64cdc56
