### ISSUE TITLE
Only .esp file when I download?

### ISSUE THREAD

**Issue by echeesy** [Odie/skyui-vr#54]
When I try to download, I only get a .esp file?

![Screenshot_24](https://user-images.githubusercontent.com/89145482/129913598-0992b7bb-749d-4365-a516-03408da0d93c.png)

**Comment by Odie** [comment]
Hi there,

Your screenshot actually shows that there is a folder to navigate into. Inside the folder, it should look something like this:

![Screen Shot 2021-08-19 at 10 50 32 AM](https://user-images.githubusercontent.com/10692/130000080-23478157-f62e-4b98-8e86-e17c75cdb9ba.png)

When unpacked, it really is about 1.7MB, as your archiver (WinRAR?) accurately reported. Installing this should be just the matter of dragging the archive into MO2.

=)
