### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by jeq1** [Odie/skyui-vr#60]
so how do i install this to skyrim vr?

**Comment by Odie** [comment]
Hi there,

Installing skyui isn’t any different from installing other mods.

> For MO2 users, use the "Install from file" icon in the toolbar.
> 
> For Vortex users, drop the .7z file over the vortex window.

I’m afraid I’m not able to help much more beyond these simple instructions. :(

If you need more help, do checkout the modding guide compendium the good people at r/SkyrimVR has put together:
https://docs.google.com/document/u/0/d/1qbh7GE30xLyso7MA6u3xpNJNdL5r2V2WP8SjZ4VpHLQ/mobilebasic

If you prefer watching a video, try this:
https://youtu.be/UztTtWs0zfQ

Good luck!

**Comment by Odie** [comment]
Closing stale issue
