### ISSUE TITLE
CTD issue

### ISSUE THREAD

**Issue by Nero0017** [Odie/skyui-vr#67]
Hello, when i activate the skyui on skyrim vr, there is a lot chance to ctd while looting, i wonder if there is any solutions?

**Comment by Odie** [comment]
Yikes. You said this happens when you’re looting. Does it happen on open or close? How often does this happen? Does this happen when you’re opening any other skyui menus?

**Comment by Nero0017** [comment]
it happens when opening the loot menu, and it happens after around 20 minutes playing. When the game crash , i restart the game and loot the same npc, and it doesn't crash ,and after around 20 minutes it happens again randomly when looting.

**Comment by Odie** [comment]
Please do try downgrading to the old  version and see if that resolves your problem. I’ll see if I can reproduce your issue.

https://github.com/Odie/skyui-vr/releases/tag/v1.0-beta.4

**Comment by Nero0017** [comment]
I reinstall the whole game and it works well this time surprisely, thank you for replying

**Comment by Nero0017** [comment]
i founded out there are some plugins has Loot Message flag in vortex, and i change the index of skyui by loading it after all plugins with Loot Message flag, and it works well for now.

**Comment by Odie** [comment]
Which plug-in in particular was causing the issue?

**Comment by Nero0017** [comment]
yesterday it probably was XPMSE，CBBE，Ordinator Perks， but I added two mods：security overhaul and vr patch, and now it ctd again

**Comment by Odie** [comment]
Have you tried it with the older version of skyui?

**Comment by Odie** [comment]
Let's try to make sure that Skyui *is* the culprit behind your crashes first, since skyim may become unstable for any number of reasons.

---

Version 1.0-beta4 includes no native code and cannot cause crashes on its own. Newer versions do include native code which *might* cause the game crashes.

So, if you switch back to ver 1.0-beta4, and the crash problem is forever gone, then we would have identified some crash issue in the newer version of skyui. If you switch back, and the problem persists, then the crash problem lies elsewhere in your setup. =)

**Comment by Nero0017** [comment]
i installed only skyui vr and skse and still ctd, both old and new version have ctd problem, and if i turn off skyui , ctd problems are gone, don't know why.

**Comment by Odie** [comment]
I’m not sure if I can be of much help in this case. The old version (1.0-b4) simply should not be crashing the game.

If you’re just getting started with modding, you might want to just use an existing [wabbajack mod list](https://www.wabbajack.org/#/modlists/gallery). It’ll get you up and running much faster.

**Comment by Nero0017** [comment]
Thank you for replying, i have used SSEEdit to delete some dirty data, and it sometimes can run without crash, thanks again for your help

**Comment by Odie** [comment]
Alrighty. You might also try asking for help in r/SkyrimVR if you’re still having trouble with it.
