### ISSUE TITLE
CTD drinking potion with HIGGS

### ISSUE THREAD

**Issue by seongcheollee94** [Odie/skyui-vr#68]
Hi. First of all, thanks for your hard work! :)

I'd like to report a very strange glitch.

How to recreate:

1. Craft a potion of restore Magicka without any additional effect. (ex. Mora tapinella + red mountain flower)
2. Drop the potion on the floor (Optionally, grab it through Spell Wheel VR)
3. Drinking the LAST potion with HIGGS (grabbing and releasing the potion near your mouth) will crash the game.

This only happens with crafted "potion of restore Magicka" (as far as I know), and with the last potion that exist in the cell.
The game does not crash if you drink the potion in the menu.
The game does not crash if SkyUI is not installed.

**Comment by AllStickyGithub** [comment]
I could reproduce this issue following the steps described. Here is a pastebin with my crashlog. Fair to say the mods are incompatible.
https://pastebin.com/Xm1PiA4K

**Comment by Odie** [comment]
Thanks for the crash log!  This has just been fixed in the latest release!

https://github.com/Odie/skyui-vr/releases/tag/v1.2.2

So sorry it took forever to fix. Better late than never? x_x

**Comment by AllStickyGithub** [comment]
A very late thank you for you XD
