### ISSUE TITLE
Says SKSEVR is not running when it is running

### ISSUE THREAD

**Issue by Church7300** [Odie/skyui-vr#72]
thats about it

**Comment by Odie** [comment]
Hi there,

sorry, I’m not entirely clear on what you mean here. 

Do you mean you’re seeing a dialog that says it’s not running, but you can actually access MCM and the skyui inventory screens?

**Comment by Giovega211** [comment]
very same problem. Sky UI error code 1 , it tells me Skse is not running, but it is running whenever i dont have Sky UI installed. 
So the problem seems to arise trough Sky UI. Any suggestions ? 
Thanks
