### ISSUE TITLE
MCM not working ingame

### ISSUE THREAD

**Issue by Roxandlol** [Odie/skyui-vr#73]
I had previous issues with SkyUI 1.2.1 and 1.2.0 where my vortex notifications were telling me I should use skse64 for SkyUI VR which doesn't make sense as I already use skseVR. I kinda fixed this issue by booting up SkyrimVR through skseVR loader as admin. I managed to get SkyUI to work ingame semi-regularly, some dependent mods still give out issue messages ingame and i am not able to configure any of the installed mods in the MCM inside the game's menu settings. When I open the tab for MCM it's completely empty and doesn't display any of my installed mods.

**Comment by Odie** [comment]
Hi there!

Please refer to this video on how to get things set up correctly.
https://youtu.be/UztTtWs0zfQ

You might want to visit r/SkyrimVR. There are lots well written guides on how to install the essentials, including SkyUI. =)

**Comment by Roxandlol** [comment]
I've got it fixed yesterday after some research. Turns out I managed to fix the bug by just reinstalling both the SkyUI and SkseVR.
The Vortex notification still pops up after I boot up the game through SkseVR but it works ingame nonetheless. I don't exactly know what caused the issue but I guess my way of fixing it could be applied to other users with the same issue. Just for future reference, I still launch SkseVR as administrator every time to make sure it works properly.

**Comment by mongchat** [comment]
bizarre - I've reinstalled SkyUI and SkseVR countless times now to try and solve this to no avail. I'm going to try a fresh installation of the game and reinstalling all the mods from the ground up then see if the issue persists.

**Comment by Odie** [comment]
It's been a while since I've had to install from scratch. If memory serves, the things that are easy to miss are:
- Launch the game through skse loader
  Without this step, skse isn't loaded at all, so it won't be able to provide its functionality to the mods.
- Install the script files that comes with skse
  Most mods call into these script files to talk to skse. Without these files, a lot of the features the mods try to provide will simply not work. The exact installation steps are different depending on which mod manager you're using.

Getting this set up always feels like the hardest thing ever.  Hope this helps a little.

**Comment by SK3DDI** [comment]
Hello there, just wanted to say I'm seeing the same issue on vortex. Could it just be a bug with vortex thinking it requires skse64? Sorry I'm new at this. Here is a screenshot maybe that can help?
![Screenshot (1)](https://user-images.githubusercontent.com/107097147/172539923-c785ee20-a20e-4438-8713-abfd15d7fa0f.png)

**Comment by Odie** [comment]
Sorry, I’ve never used vortex, so I’m not really able to help here.

Is it possible to dismiss the error and continue starting up the game?

**Comment by mongchat** [comment]
reinstalling the game and installing SKSE and SKYUIVR exactly as the above video described fixed it. my guess is i messed something up during my original installation of SKSE. It's working a charm now. thanks a bunch :)

**Comment by Odie** [comment]
Closing resolved issue.
