### ISSUE TITLE
Says it requires SKSE SE instead of SKSEVR, i have tried both, but it still says plugin dependencies unfulfilled 

### ISSUE THREAD

**Issue by jacko69** [Odie/skyui-vr#74]
Says it requires SKSE SE instead of SKSEVR, I have tried both, but it still says plugin dependencies are unfulfilled. i am using vortex.

**Comment by Odie** [comment]
Hi there!

I haven’t used vortex before, so I’m not sure what specific prompts you might run into. What is certain is that you need sksevr instead of skse se.

This video has pretty detail instructions on how to set things up. Hope it helps. :)

https://youtu.be/UztTtWs0zfQ

**Comment by Odie** [comment]
Assuming the issue had been resolved.
