### ISSUE TITLE
Can't locate the right file to drop into Vortex

### ISSUE THREAD

**Issue by GrandmaisBack** [Odie/skyui-vr#75]
So I'm not a modder, and know absolutely zero terminology. In simple terms or some I can learn. how can I get SkyUI into Vortex or Nexxus Mod Manager? I download the file in your code section and attempt to open it so I can drop it into Vortex, but I get a system notification in Vortex saying the file doesn't exist. Do I need a specific program to open the v1.2.1 File to then drop into Vortex, because I can't figure out what I'm doing wrong when I'm exactly mimicking the tutorials I am watching.

**Comment by Odie** [comment]
Hi there,

Please follow the instructions here.
https://youtu.be/UztTtWs0zfQ

You can also find various modding guides on r/SkyrimVR.

Hope that helps!

**Comment by Odie** [comment]
Closing stale issue.
