### ISSUE TITLE
sky ui vr says it needs regular skse

### ISSUE THREAD

**Issue by willflatt** [Odie/skyui-vr#76]
i have the newest version of both skse vr and sky uiv
![Screenshot 2022-07-05 021904](https://user-images.githubusercontent.com/32919702/177272196-e6e14047-bc3d-46a2-bf41-bb7e62b65e38.png)
![Screenshot 2022-07-05 022310](https://user-images.githubusercontent.com/32919702/177272672-83f1eba0-ec67-476f-bf5d-dd0033697231.png)
![Screenshot 2022-07-05 022419](https://user-images.githubusercontent.com/32919702/177272863-b5bf8634-76e0-4041-95bf-3975aa0bf12d.png)
![Screenshot 2022-07-05 022537](https://user-images.githubusercontent.com/32919702/177273135-c3c86b73-3363-4a42-8376-7db97dd1656c.png)
 those are copies i kept intact in default place for pics
any help is appreciated

**Comment by Odie** [comment]
Sorry, I don’t use vortex, so I don’t have a good answer for you. 

What happens if you just ignore the error and launch the game anyway? Is this maybe just a problem of vortex not quite understanding SkyrimVR dependencies right?
