### ISSUE TITLE
CTD when taking stamina potions with VRIK (raise hand to face and press trigger)

### ISSUE THREAD

**Issue by foxhound525** [Odie/skyui-vr#80]
I have stamina/magika potions bound to my right hand, so that when I raise my right hand to my mouth, if I then click the right trigger, it will either have me drink a stamina or magika potion. I think it prioritises stamina while that is low.

I've had about 8 instances where doing this has crashed my game, and when I checked the crashlog, every time SkyUI is the culprit.

'Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFFFAEAE151 SkyUI-VR.dll+000E151'

Please see the full log [here](https://pastebin.com/wYmjaGSE) 

Sometimes I can take the potion fine, somtimes I can take like 4 in a row with no problems. But when it decides that particular time is going to crash, it does it every time. i.e. I can save, take the potion and crash, restart/reload, and when I reload it will crash again when I take the potion. BUT if I go through the inventory menu and take every single stamina related potion I have, nothing happens.

This does not ever happen when I take healing potions on my left hand. 

I have several clips of this crash in action if needed

**Comment by Odie** [comment]
Ooookay! This has just been fixed in the latest release!

https://github.com/Odie/skyui-vr/releases/tag/v1.2.2

That wasn't so hard! It didn't even take a whole year to fix! x)
