### ISSUE TITLE
ESP Error

### ISSUE THREAD

**Issue by TangentGamingCEO** [Odie/skyui-vr#82]
It seems I am not the only one experiencing this problem. I know SkyUI VR worked years ago, but now that I am coming back to it, I am getting a dependency issue. It seems to be looking for the non-VR SKSE file. Any suggestions? I only own the VR version of the game and it is the only reason I bought the game again after so many years, to play in VR. I hope everything is okay for you, love the mod help, let me know if there is any way I can help.

![Screenshot 2022-10-24 032059](https://user-images.githubusercontent.com/116545596/197469732-36c71df1-8c16-4d75-bf15-658f6014c254.png)

**Comment by Odie** [comment]
Hi there,

I think people do report this one from time to time. I think this is just vortex not being able to differentiate between skyui and skyui-vr and which version of skse needs to be present. If skse-vr is installed correctly, please try to just launch the game anyway. Things should work fine.

**Comment by Odie** [comment]
Closing stale issue.
