### ISSUE TITLE
I think you have the Special Edition up for VR

### ISSUE THREAD

**Issue by ArsenalCake** [Odie/skyui-vr#83]
![Capture](https://user-images.githubusercontent.com/121420930/209515001-035f41b6-c7a3-41e2-96ca-7592f158f4df.PNG)
As you can see, the mod file says SE in it, no where does the zip or anything say VR, and despite the fact I launch the game with the script extender, it either tells me I dont have it or just black screens me before I see a menu. I only see Bethesda's logo before it poops out.
![Capture](https://user-images.githubusercontent.com/121420930/209515382-2b4a4cde-f8ba-406c-89e5-47f9410a37d5.PNG)
Both are current.

**Comment by Odie** [comment]
This is one of the more frequently asked questions. Please just ignore the error and launch the game anyway.

**Comment by ArsenalCake** [comment]
I load in to a perma black screen. I have even tried disabling everything else and it wont work.

**Comment by Odie** [comment]
Can you try just launching the vanilla game, then launch with only skyui activated?

**Comment by ArsenalCake** [comment]
Vanilla game works just fine, but any time I play skyui, it either tells me I am missing the script extender, or when I launch by the script extender it puts me into a perma black screen. I even tried it with just the two and its still just a perma black screen.

**Comment by ArsenalCake** [comment]
![image](https://user-images.githubusercontent.com/121420930/209608808-a8537502-3c77-4864-8cd8-959614c64dee.png)
this is what my vortex looks like

**Comment by ArsenalCake** [comment]
![image](https://user-images.githubusercontent.com/121420930/209608848-a903f391-e1b9-4962-844b-458e99460e52.png)
This is what my vortex looks like as of now, when I launch the game and get perma black. They are the only two enabled.

**Comment by ArsenalCake** [comment]
Enabling Skyrim VR tools and every other mod still greets me with a black screen. I have tried them individually and all together in many combinations but nothing works.

**Comment by Odie** [comment]
How about if you just launch with SKSE?

**Comment by firecanon** [comment]
i'm having the same issue

**Comment by firecanon** [comment]
it works when only the script extender is on but not skyui

**Comment by ArsenalCake** [comment]
Yeah script extender works, but not with sky

**Comment by Odie** [comment]
It’s quite difficult to figure out what might be wrong with your setup just from what you’re describing. It might be that it’s just the matter of script extender not being launched right. You can check if that is the case with instructions attached at the end of this post.

It’s also not unheard of for the game files to have gotten corrupted/broken somehow as mods were being installed. In that case, reinstalling the game to start fresh might help.

There are also a number of videos that walks through how to install the basics from from scratch. Please give those a look.

Regarding the mod manager, I don’t know how well vortex actually supports Skyrim UI modding these dasy. If you’re just getting started with modding, it’ll probably be less painful if you stick with MO2, which works hard to not alter any files in the game directory.

Lastly, if you’re still having trouble, please do seek help from fellow players on r/SkyrimVR. People are usually friendly and happy to help.

—-

To verify script extender, try the following:

- launch the game
- open the console with the tilde key
- type in  “getskseversion” without the quotes
- hit enter to run the command

The version number should be printed out on the console. If nothing happens, then SKSE isn’t actually running.

**Comment by realgravy** [comment]
@Odie, I launched  sksevr_loader.exe directly from steamapps\common\SkyrimVR folder and it works.

**Comment by Odie** [comment]
Closing stale issue.
