### ISSUE TITLE
SkyUI takes ~5 seconds to load in when looting corpses/chest and MCM not working

### ISSUE THREAD

**Issue by samtipton** [Odie/skyui-vr#87]
Hello, returning to play Skyrim VR again and SkyUI is acting up. I did a fresh install of the game and deleted my config directory in `Documents/mygames/Skyrim\ VR`.

I first installed sksevr latest version 2.0.12 both from website and from nexus using vortex in separate attempts to test. 

When manually getting the file for sksevr, I copied over the text files, dll and exe directory then zipped (.7z) the `Data` directory and dragged to vortex to install as instructed here: https://www.youtube.com/watch?v=UztTtWs0zfQ

Next I installed SkyUI by using the latest version here ([v1.2.1](https://github.com/Odie/skyui-vr/releases/tag/v1.2.1)).

In game, I can open my inventory instantly with no delay, but if I loot a chest or corpse there is a 5-10 second delay where I cannot enter inputs and I see only the footer section of the inventory pane before it loads in.

The MCM menu also only shows the icon and no other mods. I installed HIGGS and VRIK to test the mcm menu but still only see its icon.

**Comment by Odie** [comment]
Hi there!

It sounds like you probably forgot to install the skse script files.

:)

**Comment by samtipton** [comment]
I re-installed skse using vortex and SkyUI several times and installed Immersive Creatures because someone somewhere said that worked for them. It finally started working... Probably spent 6 hours on this. I definitely followed the installation instructions to the t. I think there is a missing step or final step to validate installation. After installing Immersive and EFLX MCM and FISSES MCM started working and SkyUI was working.
